package standard

// ISOLanguageCode means the code of language, uses [ISO 639-1], includes [RFC 1766] and [RFC 3066]
//
// example: zh, en
//
// [ISO 639-1]: https://en.wikipedia.org/wiki/ISO_639-1
// [RFC 1766]: https://datatracker.ietf.org/doc/html/rfc1766
// [RFC 3066]: https://datatracker.ietf.org/doc/html/rfc3066
type ISOLanguageCode string

// ISOLanguageCode language code enums
const (
	LanguageCodeAfar             ISOLanguageCode = "aa" // Afar 阿尔法文
	LanguageCodeAbkhazian        ISOLanguageCode = "ab" // Abkhazian 阿布哈西亚文
	languageCodeAvestan          ISOLanguageCode = "ae" // Avestan 阿维斯陀文
	LanguageCodeAfrikaans        ISOLanguageCode = "af" // Afrikaans 南非荷兰文
	LanguageCodeAkan             ISOLanguageCode = "ak" // Akan 阿肯文
	LanguageCodeAmharic          ISOLanguageCode = "am" // Amharic 阿姆哈拉文
	LanguageCodeAragonese        ISOLanguageCode = "an" // Aragonese 阿拉贡文
	LanguageCodeArabic           ISOLanguageCode = "ar" // Arabic 阿拉伯文
	LanguageCodeAssamese         ISOLanguageCode = "as" // Assamese 阿萨姆文
	LanguageCodeAvaric           ISOLanguageCode = "av" // Avaric 阿瓦尔文
	LanguageCodeAymara           ISOLanguageCode = "ay" // Aymara 艾马拉文
	LanguageCodeAzerbaijani      ISOLanguageCode = "az" // Azerbaijani 阿塞拜疆文
	LanguageCodeBashkir          ISOLanguageCode = "ba" // Bashkir 巴什基尔文
	LanguageCodeBelarusian       ISOLanguageCode = "be" // Belarusian 白俄罗斯文
	LanguageCodeBulgarian        ISOLanguageCode = "bg" // Bulgarian 保加利亚文
	LanguageCodeBihari           ISOLanguageCode = "bh" // Bihari 比哈尔文
	LanguageCodeBislama          ISOLanguageCode = "bi" // Bislama 比斯拉马文
	LanguageCodeBambara          ISOLanguageCode = "bm" // Bambara 班巴拉文
	LanguageCodeBengali          ISOLanguageCode = "bn" // Bengali 孟加拉文
	LanguageCodeTibetan          ISOLanguageCode = "bo" // Tibetan 藏文
	LanguageCodeBreton           ISOLanguageCode = "br" // Breton 布列塔尼文
	LanguageCodeBosnian          ISOLanguageCode = "bs" // Bosnian 波斯尼亚文
	LanguageCodeCatalan          ISOLanguageCode = "ca" // Catalan 加泰罗尼亚文
	LanguageCodeChechen          ISOLanguageCode = "ce" // Chechen 车臣文
	LanguageCodeChamorro         ISOLanguageCode = "ch" // Chamorro 查莫罗文
	LanguageCodeCorsican         ISOLanguageCode = "co" // Corsican 科西嘉文
	LanguageCodeCree             ISOLanguageCode = "cr" // Cree 克里文
	LanguageCodeCzech            ISOLanguageCode = "cs" // Czech 捷克文
	LanguageCodeChurchSlavic     ISOLanguageCode = "cu" // Church Slavic 教会斯拉夫文
	LanguageCodeChuvash          ISOLanguageCode = "cv" // Chuvash 楚瓦什文
	LanguageCodeWelsh            ISOLanguageCode = "cy" // Welsh 威尔士文
	LanguageCodeDanish           ISOLanguageCode = "da" // Danish 丹麦文
	LanguageCodeGerman           ISOLanguageCode = "de" // German 德文
	LanguageCodeDivehi           ISOLanguageCode = "dv" // Divehi 迪维希文
	LanguageCodeDzongkha         ISOLanguageCode = "dz" // Dzongkha 宗卡文
	LanguageCodeEwe              ISOLanguageCode = "ee" // Ewe 埃维文
	LanguageCodeGreek            ISOLanguageCode = "el" // Greek 希腊文
	LanguageCodeEnglish          ISOLanguageCode = "en" // English 英文
	LanguageCodeEsperanto        ISOLanguageCode = "eo" // Esperanto 世界语
	LanguageCodeSpanish          ISOLanguageCode = "es" // Spanish 西班牙文
	LanguageCodeEstonian         ISOLanguageCode = "et" // Estonian 爱沙尼亚文
	LanguageCodeBasque           ISOLanguageCode = "eu" // Basque 巴斯克文
	LanguageCodePersian          ISOLanguageCode = "fa" // Persian 波斯文
	LanguageCodeFulah            ISOLanguageCode = "ff" // Fulah 富拉文
	LanguageCodeFinnish          ISOLanguageCode = "fi" // Finnish 芬兰文
	LanguageCodeFijian           ISOLanguageCode = "fj" // Fijian 斐济文
	LanguageCodeFaroese          ISOLanguageCode = "fo" // Faroese 法罗文
	LanguageCodeFrench           ISOLanguageCode = "fr" // French 法文
	LanguageCodeWesternFrisian   ISOLanguageCode = "fy" // Western Frisian 弗里西亚文
	LanguageCodeIrish            ISOLanguageCode = "ga" // Irish 爱尔兰文
	LanguageCodeScottishGaelic   ISOLanguageCode = "gd" // Scottish Gaelic 苏格兰盖尔文
	LanguageCodeGalician         ISOLanguageCode = "gl" // Galician 加利西亚文
	LanguageCodeGuarani          ISOLanguageCode = "gn" // Guarani 瓜拉尼文
	LanguageCodeGujarati         ISOLanguageCode = "gu" // Gujarati 古吉拉特文
	LanguageCodeManx             ISOLanguageCode = "gv" // Manx 曼岛文
	LanguageCodeHausa            ISOLanguageCode = "ha" // Hausa 豪萨文
	LanguageCodeHebrew           ISOLanguageCode = "he" // Hebrew 希伯来文
	LanguageCodeHindi            ISOLanguageCode = "hi" // Hindi 印地文
	LanguageCodeHiriMotu         ISOLanguageCode = "ho" // Hiri Motu 希里莫图文
	LanguageCodeCroatian         ISOLanguageCode = "hr" // Croatian 克罗地亚文
	LanguageCodeHaitian          ISOLanguageCode = "ht" // Haitian 海地文
	LanguageCodeHungarian        ISOLanguageCode = "hu" // Hungarian 匈牙利文
	LanguageCodeArmenian         ISOLanguageCode = "hy" // Armenian 亚美尼亚文
	LanguageCodeHerero           ISOLanguageCode = "hz" // Herero 赫雷罗文
	LanguageCodeInterlingua      ISOLanguageCode = "ia" // Interlingua 国际语
	LanguageCodeIndonesian       ISOLanguageCode = "id" // Indonesian 印尼文
	LanguageCodeInterlingue      ISOLanguageCode = "ie" // Interlingue 国际文
	LanguageCodeIgbo             ISOLanguageCode = "ig" // Igbo 伊博文
	LanguageCodeSichuanYi        ISOLanguageCode = "ii" // Sichuan Yi 彝文
	LanguageCodeInupiaq          ISOLanguageCode = "ik" // Inupiaq 因纽特文
	LanguageCodeIdo              ISOLanguageCode = "io" // Ido 伊多文
	LanguageCodeIcelandic        ISOLanguageCode = "is" // Icelandic 冰岛文
	LanguageCodeItalian          ISOLanguageCode = "it" // Italian 意大利文
	LanguageCodeInuktitut        ISOLanguageCode = "iu" // Inuktitut 因纽特文
	LanguageCodeJapanese         ISOLanguageCode = "ja" // Japanese 日文
	LanguageCodeJavanese         ISOLanguageCode = "jv" // Javanese 爪哇文
	LanguageCodeGeorgian         ISOLanguageCode = "ka" // Georgian 格鲁吉亚文
	LanguageCodeKongo            ISOLanguageCode = "kg" // Kongo 刚果文
	LanguageCodeKikuyu           ISOLanguageCode = "ki" // Kikuyu 基库尤文
	LanguageCodeKuanyama         ISOLanguageCode = "kj" // Kuanyama 宽亚玛文
	LanguageCodeKazakh           ISOLanguageCode = "kk" // Kazakh 哈萨克文
	LanguageCodeKalaallisut      ISOLanguageCode = "kl" // Kalaallisut 格陵兰文
	LanguageCodeKhmer            ISOLanguageCode = "km" // Khmer 高棉文
	LanguageCodeKannada          ISOLanguageCode = "kn" // Kannada 坎纳达文
	LanguageCodeKorean           ISOLanguageCode = "ko" // Korean 韩文
	LanguageCodeKanuri           ISOLanguageCode = "kr" // Kanuri 卡努里文
	LanguageCodeKashmiri         ISOLanguageCode = "ks" // Kashmiri 克什米尔文
	LanguageCodeKurdish          ISOLanguageCode = "ku" // Kurdish 库尔德文
	LanguageCodeKomi             ISOLanguageCode = "kv" // Komi 科米文
	LanguageCodeCornish          ISOLanguageCode = "kw" // Cornish 康沃尔文
	LanguageCodeKirghiz          ISOLanguageCode = "ky" // Kirghiz 吉尔吉斯文
	LanguageCodeLatin            ISOLanguageCode = "la" // Latin 拉丁文
	LanguageCodeLuxembourgish    ISOLanguageCode = "lb" // Luxembourgish 卢森堡文
	LanguageCodeGanda            ISOLanguageCode = "lg" // Ganda 卢干达文
	LanguageCodeLimburgish       ISOLanguageCode = "li" // Limburgish 林堡文
	LanguageCodeLingala          ISOLanguageCode = "ln" // Lingala 林加拉文
	LanguageCodeLao              ISOLanguageCode = "lo" // Lao 老挝文
	LanguageCodeLithuanian       ISOLanguageCode = "lt" // Lithuanian 立陶宛文
	LanguageCodeLubaKatanga      ISOLanguageCode = "lu" // Luba-Katanga 卢巴加丹加文
	LanguageCodeLatvian          ISOLanguageCode = "lv" // Latvian 拉脱维亚文
	LanguageCodeMalagasy         ISOLanguageCode = "mg" // Malagasy 马达加斯加文
	LanguageCodeMarshallese      ISOLanguageCode = "mh" // Marshallese 马绍尔文
	LanguageCodeMaori            ISOLanguageCode = "mi" // Maori 毛利文
	LanguageCodeMacedonian       ISOLanguageCode = "mk" // Macedonian 马其顿文
	LanguageCodeMalayalam        ISOLanguageCode = "ml" // Malayalam 马拉雅拉姆文
	LanguageCodeMongolian        ISOLanguageCode = "mn" // Mongolian 蒙古文
	LanguageCodeMarathi          ISOLanguageCode = "mr" // Marathi 马拉提文
	LanguageCodeMalay            ISOLanguageCode = "ms" // Malay 马来文
	LanguageCodeMaltese          ISOLanguageCode = "mt" // Maltese 马耳他文
	LanguageCodeBurmese          ISOLanguageCode = "my" // Burmese 缅甸文
	LanguageCodeNauru            ISOLanguageCode = "na" // Nauru 瑙鲁文
	LanguageCodeNorwegianBokmal  ISOLanguageCode = "nb" // Norwegian Bokmål 挪威博克马尔文
	LanguageCodeNorthNdebele     ISOLanguageCode = "nd" // North Ndebele 北恩德贝勒文
	LanguageCodeNepali           ISOLanguageCode = "ne" // Nepali 尼泊尔文
	LanguageCodeNdonga           ISOLanguageCode = "ng" // Ndonga 恩敦加文
	LanguageCodeDutch            ISOLanguageCode = "nl" // Dutch 荷兰文
	LanguageCodeNorwegianNynorsk ISOLanguageCode = "nn" // Norwegian Nynorsk 挪威尼诺斯克文
	LanguageCodeNorwegian        ISOLanguageCode = "no" // Norwegian 挪威文
	LanguageCodeSouthNdebele     ISOLanguageCode = "nr" // South Ndebele 南恩德贝勒文
	LanguageCodeNavajo           ISOLanguageCode = "nv" // Navajo 纳瓦霍文
	LanguageCodeChichewa         ISOLanguageCode = "ny" // Chichewa 齐切瓦文
	LanguageCodeOccitan          ISOLanguageCode = "oc" // Occitan 奥克西唐文
	LanguageCodeOjibwe           ISOLanguageCode = "oj" // Ojibwe 奥吉布瓦文
	LanguageCodeOromo            ISOLanguageCode = "om" // Oromo 奥洛莫文
	LanguageCodeOriya            ISOLanguageCode = "or" // Oriya 奥里亚文
	LanguageCodeOssetian         ISOLanguageCode = "os" // Ossetian 奥塞梯文
	LanguageCodePunjabi          ISOLanguageCode = "pa" // Punjabi 旁遮普文
	LanguageCodePali             ISOLanguageCode = "pi" // Pali 巴利文
	LanguageCodePolish           ISOLanguageCode = "pl" // Polish 波兰文
	LanguageCodePashto           ISOLanguageCode = "ps" // Pashto 普什图文
	LanguageCodePortuguese       ISOLanguageCode = "pt" // Portuguese 葡萄牙文
	LanguageCodeQuechua          ISOLanguageCode = "qu" // Quechua 凯楚亚文
	LanguageCodeRomansh          ISOLanguageCode = "rm" // Romansh 罗曼什文
	LanguageCodeRundi            ISOLanguageCode = "rn" // Rundi 隆迪文
	LanguageCodeRomanian         ISOLanguageCode = "ro" // Romanian 罗马尼亚文
	LanguageCodeRussian          ISOLanguageCode = "ru" // Russian 俄文
	LanguageCodeKinyarwanda      ISOLanguageCode = "rw" // Kinyarwanda 卢旺达文
	LanguageCodeSanskrit         ISOLanguageCode = "sa" // Sanskrit 梵文
	LanguageCodeSardinian        ISOLanguageCode = "sc" // Sardinian 萨丁文
	LanguageCodeSindhi           ISOLanguageCode = "sd" // Sindhi 信德文
	LanguageCodeNorthernSami     ISOLanguageCode = "se" // Northern Sami 北萨米文
	LanguageCodeSango            ISOLanguageCode = "sg" // Sango 桑戈文
	LanguageCodeSinhala          ISOLanguageCode = "si" // Sinhala 僧伽罗文
	LanguageCodeSlovak           ISOLanguageCode = "sk" // Slovak 斯洛伐克文
	LanguageCodeSlovenian        ISOLanguageCode = "sl" // Slovenian 斯洛文尼亚文
	LanguageCodeSamoan           ISOLanguageCode = "sm" // Samoan 萨摩亚文
	LanguageCodeShona            ISOLanguageCode = "sn" // Shona 绍纳文
	LanguageCodeSomali           ISOLanguageCode = "so" // Somali 索马里文
	LanguageCodeAlbanian         ISOLanguageCode = "sq" // Albanian 阿尔巴尼亚文
	LanguageCodeSerbian          ISOLanguageCode = "sr" // Serbian 塞尔维亚文
	LanguageCodeSwati            ISOLanguageCode = "ss" // Swati 斯瓦特文
	LanguageCodeSotho            ISOLanguageCode = "st" // Sotho 塞索托文
	LanguageCodeSundanese        ISOLanguageCode = "su" // Sundanese 巽他文
	LanguageCodeSwedish          ISOLanguageCode = "sv" // Swedish 瑞典文
	LanguageCodeSwahili          ISOLanguageCode = "sw" // Swahili 斯瓦希里文
	LanguageCodeTamil            ISOLanguageCode = "ta" // Tamil 泰米尔文
	LanguageCodeTelugu           ISOLanguageCode = "te" // Telugu 泰卢固文
	LanguageCodeTajik            ISOLanguageCode = "tg" // Tajik 塔吉克文
	LanguageCodeThai             ISOLanguageCode = "th" // Thai 泰文
	LanguageCodeTigrinya         ISOLanguageCode = "ti" // Tigrinya 提格利尼亚文
	LanguageCodeTurkmen          ISOLanguageCode = "tk" // Turkmen 土库曼文
	LanguageCodeTagalog          ISOLanguageCode = "tl" // Tagalog 塔加洛文
	LanguageCodeTswana           ISOLanguageCode = "tn" // Tswana 茨瓦纳文
	LanguageCodeTonga            ISOLanguageCode = "to" // Tonga 汤加文
	LanguageCodeTurkish          ISOLanguageCode = "tr" // Turkish 土耳其文
	LanguageCodeTsonga           ISOLanguageCode = "ts" // Tsonga 聪加文
	LanguageCodeTatar            ISOLanguageCode = "tt" // Tatar 鞑靼文
	LanguageCodeTwi              ISOLanguageCode = "tw" // Twi 契维文
	LanguageCodeTahitian         ISOLanguageCode = "ty" // Tahitian 塔希提文
	LanguageCodeUighur           ISOLanguageCode = "ug" // Uighur 维吾尔文
	LanguageCodeUkrainian        ISOLanguageCode = "uk" // Ukrainian 乌克兰文
	LanguageCodeUrdu             ISOLanguageCode = "ur" // Urdu 乌尔都文
	LanguageCodeUzbek            ISOLanguageCode = "uz" // Uzbek 乌兹别克文
	LanguageCodeVenda            ISOLanguageCode = "ve" // Venda 文达文
	LanguageCodeVietnamese       ISOLanguageCode = "vi" // Vietnamese 越南文
	LanguageCodeVolapuk          ISOLanguageCode = "vo" // Volapük 沃拉普克文
	LanguageCodeWalloon          ISOLanguageCode = "wa" // Walloon 瓦隆文
	LanguageCodeWolof            ISOLanguageCode = "wo" // Wolof 沃洛夫文
	LanguageCodeXhosa            ISOLanguageCode = "xh" // Xhosa 科萨文
	LanguageCodeYiddish          ISOLanguageCode = "yi" // Yiddish 依地文
	LanguageCodeYoruba           ISOLanguageCode = "yo" // Yoruba 约鲁巴文
	LanguageCodeZhuang           ISOLanguageCode = "za" // Zhuang 壮文
	LanguageCodeChinese          ISOLanguageCode = "zh" // Chinese 中文
	LanguageCodeZulu             ISOLanguageCode = "zu" // Zulu 祖鲁文
)
