package standard

// ISORegionCode means the code of a region, uses [ISO 3166-1 alpha-2]
//
// example: CN, US, JP, GB
//
// [ISO 3166-1 alpha-2]: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
type ISORegionCode string

// ISORegionCode region code enums
const (
	RegionCodeAndorra                          ISORegionCode = "AD" // Andorra 安道尔
	RegionCodeUnitedArabEmirates               ISORegionCode = "AE" // United Arab Emirates 阿联酋
	RegionCodeAfghanistan                      ISORegionCode = "AF" // Afghanistan 阿富汗
	RegionCodeAntiguaBarbuda                   ISORegionCode = "AG" // Antigua and Barbuda 安提瓜和巴布达
	RegionCodeAnguilla                         ISORegionCode = "AI" // Anguilla 安圭拉
	RegionCodeAlbania                          ISORegionCode = "AL" // Albania 阿尔巴尼亚
	RegionCodeArmenia                          ISORegionCode = "AM" // Armenia 亚美尼亚
	RegionCodeAngola                           ISORegionCode = "AO" // Angola 安哥拉
	RegionCodeAntarctica                       ISORegionCode = "AQ" // Antarctica 南极洲
	RegionCodeArgentina                        ISORegionCode = "AR" // Argentina 阿根廷
	RegionCodeAmericanSamoa                    ISORegionCode = "AS" // American Samoa 美属萨摩亚
	RegionCodeAustria                          ISORegionCode = "AT" // Austria 奥地利
	RegionCodeAustralia                        ISORegionCode = "AU" // Australia 澳大利亚
	RegionCodeAruba                            ISORegionCode = "AW" // Aruba 阿鲁巴
	RegionCodeAlandIslands                     ISORegionCode = "AX" // Åland Islands 奥兰群岛
	RegionCodeAzerbaijan                       ISORegionCode = "AZ" // Azerbaijan 阿塞拜疆
	RegionCodeBosniaHerzegovina                ISORegionCode = "BA" // Bosnia and Herzegovina 波斯尼亚和黑塞哥维那
	RegionCodeBarbados                         ISORegionCode = "BB" // Barbados 巴巴多斯
	RegionCodeBangladesh                       ISORegionCode = "BD" // Bangladesh 孟加拉国
	RegionCodeBelgium                          ISORegionCode = "BE" // Belgium 比利时
	RegionCodeBurkinaFaso                      ISORegionCode = "BF" // Burkina Faso 布基纳法索
	RegionCodeBulgaria                         ISORegionCode = "BG" // Bulgaria 保加利亚
	RegionCodeBahrain                          ISORegionCode = "BH" // Bahrain 巴林
	RegionCodeBurundi                          ISORegionCode = "BI" // Burundi 布隆迪
	RegionCodeBenin                            ISORegionCode = "BJ" // Benin 贝宁
	RegionCodeSaintBarthelemy                  ISORegionCode = "BL" // Saint Barthélemy 圣巴泰勒米
	RegionCodeBermuda                          ISORegionCode = "BM" // Bermuda 百慕大
	RegionCodeBrunei                           ISORegionCode = "BN" // Brunei 文莱
	RegionCodeBolivia                          ISORegionCode = "BO" // Bolivia 玻利维亚
	RegionCodeCaribbeanNetherlands             ISORegionCode = "BQ" // Caribbean Netherlands 加勒比荷兰
	RegionCodeBrazil                           ISORegionCode = "BR" // Brazil 巴西
	RegionCodeBahamas                          ISORegionCode = "BS" // Bahamas 巴哈马
	RegionCodeBhutan                           ISORegionCode = "BT" // Bhutan 不丹
	RegionCodeBouvetIsland                     ISORegionCode = "BV" // Bouvet Island 布韦岛
	RegionCodeBotswana                         ISORegionCode = "BW" // Botswana 博茨瓦纳
	RegionCodeBelarus                          ISORegionCode = "BY" // Belarus 白俄罗斯
	RegionCodeBelize                           ISORegionCode = "BZ" // Belize 伯利兹
	RegionCodeCanada                           ISORegionCode = "CA" // Canada 加拿大
	RegionCodeCocosIslands                     ISORegionCode = "CC" // Cocos Islands 科科斯群岛
	RegionCodeDemocraticRepublicCongo          ISORegionCode = "CD" // Democratic Republic of the Congo 刚果（金）
	RegionCodeCentralAfricanRepublic           ISORegionCode = "CF" // Central African Republic 中非
	RegionCodeRepublicCongo                    ISORegionCode = "CG" // Republic of the Congo 刚果（布）
	RegionCodeSwitzerland                      ISORegionCode = "CH" // Switzerland 瑞士
	RegionCodeIvoryCoast                       ISORegionCode = "CI" // Ivory Coast 科特迪瓦
	RegionCodeCookIslands                      ISORegionCode = "CK" // Cook Islands 库克群岛
	RegionCodeChile                            ISORegionCode = "CL" // Chile 智利
	RegionCodeCameroon                         ISORegionCode = "CM" // Cameroon 喀麦隆
	RegionCodeChina                            ISORegionCode = "CN" // China 中国
	RegionCodeColombia                         ISORegionCode = "CO" // Colombia 哥伦比亚
	RegionCodeCostaRica                        ISORegionCode = "CR" // Costa Rica 哥斯达黎加
	RegionCodeCuba                             ISORegionCode = "CU" // Cuba 古巴
	RegionCodeCapeVerde                        ISORegionCode = "CV" // Cape Verde 佛得角
	RegionCodeCuracao                          ISORegionCode = "CW" // Curaçao 库拉索
	RegionCodeChristmasIsland                  ISORegionCode = "CX" // Christmas Island 圣诞岛
	RegionCodeCyprus                           ISORegionCode = "CY" // Cyprus 塞浦路斯
	RegionCodeCzechRepublic                    ISORegionCode = "CZ" // Czech Republic 捷克
	RegionCodeGermany                          ISORegionCode = "DE" // Germany 德国
	RegionCodeDjibouti                         ISORegionCode = "DJ" // Djibouti 吉布提
	RegionCodeDenmark                          ISORegionCode = "DK" // Denmark 丹麦
	RegionCodeDominica                         ISORegionCode = "DM" // Dominica 多米尼克
	RegionCodeDominicanRepublic                ISORegionCode = "DO" // Dominican Republic 多米尼加
	RegionCodeAlgeria                          ISORegionCode = "DZ" // Algeria 阿尔及利亚
	RegionCodeEcuador                          ISORegionCode = "EC" // Ecuador 厄瓜多尔
	RegionCodeEstonia                          ISORegionCode = "EE" // Estonia 爱沙尼亚
	RegionCodeEgypt                            ISORegionCode = "EG" // Egypt 埃及
	RegionCodeWesternSahara                    ISORegionCode = "EH" // Western Sahara 西撒哈拉
	RegionCodeEritrea                          ISORegionCode = "ER" // Eritrea 厄立特里亚
	RegionCodeSpain                            ISORegionCode = "ES" // Spain 西班牙
	RegionCodeEthiopia                         ISORegionCode = "ET" // Ethiopia 埃塞俄比亚
	RegionCodeFinland                          ISORegionCode = "FI" // Finland 芬兰
	RegionCodeFiji                             ISORegionCode = "FJ" // Fiji 斐济
	RegionCodeFalklandIslands                  ISORegionCode = "FK" // Falkland Islands 福克兰群岛
	RegionCodeMicronesia                       ISORegionCode = "FM" // Micronesia 密克罗尼西亚
	RegionCodeFaroeIslands                     ISORegionCode = "FO" // Faroe Islands 法罗群岛
	RegionCodeFrance                           ISORegionCode = "FR" // France 法国
	RegionCodeGabon                            ISORegionCode = "GA" // Gabon 加蓬
	RegionCodeUnitedKingdom                    ISORegionCode = "GB" // United Kingdom 英国
	RegionCodeGrenada                          ISORegionCode = "GD" // Grenada 格林纳达
	RegionCodeGeorgia                          ISORegionCode = "GE" // Georgia 格鲁吉亚
	RegionCodeFrenchGuiana                     ISORegionCode = "GF" // French Guiana 法属圭亚那
	RegionCodeGuernsey                         ISORegionCode = "GG" // Guernsey 根西
	RegionCodeGhana                            ISORegionCode = "GH" // Ghana 加纳
	RegionCodeGibraltar                        ISORegionCode = "GI" // Gibraltar 直布罗陀
	RegionCodeGreenland                        ISORegionCode = "GL" // Greenland 格陵兰
	RegionCodeGambia                           ISORegionCode = "GM" // Gambia 冈比亚
	RegionCodeGuinea                           ISORegionCode = "GN" // Guinea 几内亚
	RegionCodeGuadeloupe                       ISORegionCode = "GP" // Guadeloupe 瓜德罗普
	RegionCodeEquatorialGuinea                 ISORegionCode = "GQ" // Equatorial Guinea 赤道几内亚
	RegionCodeGreece                           ISORegionCode = "GR" // Greece 希腊
	RegionCodeSouthGeorgia                     ISORegionCode = "GS" // South Georgia and the South Sandwich Islands 南乔治亚和南桑威奇群岛
	RegionCodeGuatemala                        ISORegionCode = "GT" // Guatemala 危地马拉
	RegionCodeGuam                             ISORegionCode = "GU" // Guam 关岛
	RegionCodeGuineaBissau                     ISORegionCode = "GW" // Guinea-Bissau 几内亚比绍
	RegionCodeGuyana                           ISORegionCode = "GY" // Guyana 圭亚那
	RegionCodeHongKong                         ISORegionCode = "HK" // Hong Kong 香港
	RegionCodeHeardIsland                      ISORegionCode = "HM" // Heard Island and McDonald Islands 赫德岛和麦克唐纳群岛
	RegionCodeHonduras                         ISORegionCode = "HN" // Honduras 洪都拉斯
	RegionCodeCroatia                          ISORegionCode = "HR" // Croatia 克罗地亚
	RegionCodeHaiti                            ISORegionCode = "HT" // Haiti 海地
	RegionCodeHungary                          ISORegionCode = "HU" // Hungary 匈牙利
	RegionCodeIndonesia                        ISORegionCode = "ID" // Indonesia 印度尼西亚
	RegionCodeIreland                          ISORegionCode = "IE" // Ireland 爱尔兰
	RegionCodeIsrael                           ISORegionCode = "IL" // Israel 以色列
	RegionCodeIsleOfMan                        ISORegionCode = "IM" // Isle of Man 马恩岛
	RegionCodeIndia                            ISORegionCode = "IN" // India 印度
	RegionCodeBritishIndianOcean               ISORegionCode = "IO" // British Indian Ocean Territory 英属印度洋领地
	RegionCodeIraq                             ISORegionCode = "IQ" // Iraq 伊拉克
	RegionCodeIran                             ISORegionCode = "IR" // Iran 伊朗
	RegionCodeIceland                          ISORegionCode = "IS" // Iceland 冰岛
	RegionCodeItaly                            ISORegionCode = "IT" // Italy 意大利
	RegionCodeJersey                           ISORegionCode = "JE" // Jersey 泽西
	RegionCodeJamaica                          ISORegionCode = "JM" // Jamaica 牙买加
	RegionCodeJordan                           ISORegionCode = "JO" // Jordan 约旦
	RegionCodeJapan                            ISORegionCode = "JP" // Japan 日本
	RegionCodeKenya                            ISORegionCode = "KE" // Kenya 肯尼亚
	RegionCodeKyrgyzstan                       ISORegionCode = "KG" // Kyrgyzstan 吉尔吉斯斯坦
	RegionCodeCambodia                         ISORegionCode = "KH" // Cambodia 柬埔寨
	RegionCodeKiribati                         ISORegionCode = "KI" // Kiribati 基里巴斯
	RegionCodeComoros                          ISORegionCode = "KM" // Comoros 科摩罗
	RegionCodeSaintKittsNevis                  ISORegionCode = "KN" // Saint Kitts and Nevis 圣基茨和尼维斯
	RegionCodeNorthKorea                       ISORegionCode = "KP" // North Korea 朝鲜
	RegionCodeSouthKorea                       ISORegionCode = "KR" // South Korea 韩国
	RegionCodeKuwait                           ISORegionCode = "KW" // Kuwait 科威特
	RegionCodeCaymanIslands                    ISORegionCode = "KY" // Cayman Islands 开曼群岛
	RegionCodeKazakhstan                       ISORegionCode = "KZ" // Kazakhstan 哈萨克斯坦
	RegionCodeLaos                             ISORegionCode = "LA" // Laos 老挝
	RegionCodeLebanon                          ISORegionCode = "LB" // Lebanon 黎巴嫩
	RegionCodeSaintLucia                       ISORegionCode = "LC" // Saint Lucia 圣卢西亚
	RegionCodeLiechtenstein                    ISORegionCode = "LI" // Liechtenstein 列支敦士登
	RegionCodeSriLanka                         ISORegionCode = "LK" // Sri Lanka 斯里兰卡
	RegionCodeLiberia                          ISORegionCode = "LR" // Liberia 利比里亚
	RegionCodeLesotho                          ISORegionCode = "LS" // Lesotho 莱索托
	RegionCodeLithuania                        ISORegionCode = "LT" // Lithuania 立陶宛
	RegionCodeLuxembourg                       ISORegionCode = "LU" // Luxembourg 卢森堡
	RegionCodeLatvia                           ISORegionCode = "LV" // Latvia 拉脱维亚
	RegionCodeLibya                            ISORegionCode = "LY" // Libya 利比亚
	RegionCodeMorocco                          ISORegionCode = "MA" // Morocco 摩洛哥
	RegionCodeMonaco                           ISORegionCode = "MC" // Monaco 摩纳哥
	RegionCodeMoldova                          ISORegionCode = "MD" // Moldova 摩尔多瓦
	RegionCodeMontenegro                       ISORegionCode = "ME" // Montenegro 黑山
	RegionCodeSaintMartin                      ISORegionCode = "MF" // Saint Martin 圣马丁
	RegionCodeMadagascar                       ISORegionCode = "MG" // Madagascar 马达加斯加
	RegionCodeMarshallIslands                  ISORegionCode = "MH" // Marshall Islands 马绍尔群岛
	RegionCodeNorthMacedonia                   ISORegionCode = "MK" // North Macedonia 北马其顿
	RegionCodeMali                             ISORegionCode = "ML" // Mali 马里
	RegionCodeMyanmar                          ISORegionCode = "MM" // Myanmar 缅甸
	RegionCodeMongolia                         ISORegionCode = "MN" // Mongolia 蒙古
	RegionCodeMacao                            ISORegionCode = "MO" // Macao 澳门
	RegionCodeNorthernMarianaIslands           ISORegionCode = "MP" // Northern Mariana Islands 北马里亚纳群岛
	RegionCodeMartinique                       ISORegionCode = "MQ" // Martinique 马提尼克
	RegionCodeMauritania                       ISORegionCode = "MR" // Mauritania 毛里塔尼亚
	RegionCodeMontserrat                       ISORegionCode = "MS" // Montserrat 蒙特塞拉特
	RegionCodeMalta                            ISORegionCode = "MT" // Malta 马耳他
	RegionCodeMauritius                        ISORegionCode = "MU" // Mauritius 毛里求斯
	RegionCodeMaldives                         ISORegionCode = "MV" // Maldives 马尔代夫
	RegionCodeMalawi                           ISORegionCode = "MW" // Malawi 马拉维
	RegionCodeMexico                           ISORegionCode = "MX" // Mexico 墨西哥
	RegionCodeMalaysia                         ISORegionCode = "MY" // Malaysia 马来西亚
	RegionCodeMozambique                       ISORegionCode = "MZ" // Mozambique 莫桑比克
	RegionCodeNamibia                          ISORegionCode = "NA" // Namibia 纳米比亚
	RegionCodeNewCaledonia                     ISORegionCode = "NC" // New Caledonia 新喀里多尼亚
	RegionCodeNiger                            ISORegionCode = "NE" // Niger 尼日尔
	RegionCodeNorfolkIsland                    ISORegionCode = "NF" // Norfolk Island 诺福克岛
	RegionCodeNigeria                          ISORegionCode = "NG" // Nigeria 尼日利亚
	RegionCodeNicaragua                        ISORegionCode = "NI" // Nicaragua 尼加拉瓜
	RegionCodeNetherlands                      ISORegionCode = "NL" // Netherlands 荷兰
	RegionCodeNorway                           ISORegionCode = "NO" // Norway 挪威
	RegionCodeNepal                            ISORegionCode = "NP" // Nepal 尼泊尔
	RegionCodeNauru                            ISORegionCode = "NR" // Nauru 瑙鲁
	RegionCodeNiue                             ISORegionCode = "NU" // Niue 纽埃
	RegionCodeNewZealand                       ISORegionCode = "NZ" // New Zealand 新西兰
	RegionCodeOman                             ISORegionCode = "OM" // Oman 阿曼
	RegionCodePanama                           ISORegionCode = "PA" // Panama 巴拿马
	RegionCodePeru                             ISORegionCode = "PE" // Peru 秘鲁
	RegionCodeFrenchPolynesia                  ISORegionCode = "PF" // French Polynesia 法属波利尼西亚
	RegionCodePapuaNewGuinea                   ISORegionCode = "PG" // Papua New Guinea 巴布亚新几内亚
	RegionCodePhilippines                      ISORegionCode = "PH" // Philippines 菲律宾
	RegionCodePakistan                         ISORegionCode = "PK" // Pakistan 巴基斯坦
	RegionCodePoland                           ISORegionCode = "PL" // Poland 波兰
	RegionCodeSaintPierreMiquelon              ISORegionCode = "PM" // Saint Pierre and Miquelon 圣皮埃尔和密克隆群岛
	RegionCodePitcairnIslands                  ISORegionCode = "PN" // Pitcairn Islands 皮特凯恩群岛
	RegionCodePuertoRico                       ISORegionCode = "PR" // Puerto Rico 波多黎各
	RegionCodePalestinianTerritories           ISORegionCode = "PS" // Palestinian Territories 巴勒斯坦领土
	RegionCodePortugal                         ISORegionCode = "PT" // Portugal 葡萄牙
	RegionCodePalau                            ISORegionCode = "PW" // Palau 帕劳
	RegionCodeParaguay                         ISORegionCode = "PY" // Paraguay 巴拉圭
	RegionCodeQatar                            ISORegionCode = "QA" // Qatar 卡塔尔
	RegionCodeReunion                          ISORegionCode = "RE" // Réunion 留尼汪
	RegionCodeRomania                          ISORegionCode = "RO" // Romania 罗马尼亚
	RegionCodeSerbia                           ISORegionCode = "RS" // Serbia 塞尔维亚
	RegionCodeRussia                           ISORegionCode = "RU" // Russia 俄罗斯
	RegionCodeRwanda                           ISORegionCode = "RW" // Rwanda 卢旺达
	RegionCodeSaudiArabia                      ISORegionCode = "SA" // Saudi Arabia 沙特阿拉伯
	RegionCodeSolomonIslands                   ISORegionCode = "SB" // Solomon Islands 所罗门群岛
	RegionCodeSeychelles                       ISORegionCode = "SC" // Seychelles 塞舌尔
	RegionCodeSudan                            ISORegionCode = "SD" // Sudan 苏丹
	RegionCodeSweden                           ISORegionCode = "SE" // Sweden 瑞典
	RegionCodeSingapore                        ISORegionCode = "SG" // Singapore 新加坡
	RegionCodeSaintHelena                      ISORegionCode = "SH" // Saint Helena 圣赫勒拿
	RegionCodeSlovenia                         ISORegionCode = "SI" // Slovenia 斯洛文尼亚
	RegionCodeSvalbardJanMayen                 ISORegionCode = "SJ" // Svalbard and Jan Mayen 斯瓦尔巴特群岛和扬马延岛
	RegionCodeSlovakia                         ISORegionCode = "SK" // Slovakia 斯洛伐克
	RegionCodeSierraLeone                      ISORegionCode = "SL" // Sierra Leone 塞拉利昂
	RegionCodeSanMarino                        ISORegionCode = "SM" // San Marino 圣马力诺
	RegionCodeSenegal                          ISORegionCode = "SN" // Senegal 塞内加尔
	RegionCodeSomalia                          ISORegionCode = "SO" // Somalia 索马里
	RegionCodeSuriname                         ISORegionCode = "SR" // Suriname 苏里南
	RegionCodeSouthSudan                       ISORegionCode = "SS" // South Sudan 南苏丹
	RegionCodeSaoTomePrincipe                  ISORegionCode = "ST" // São Tomé and Príncipe 圣多美和普林西比
	RegionCodeElSalvador                       ISORegionCode = "SV" // El Salvador 萨尔瓦多
	RegionCodeSintMaarten                      ISORegionCode = "SX" // Sint Maarten 圣马丁（荷兰部分）
	RegionCodeSyria                            ISORegionCode = "SY" // Syria 叙利亚
	RegionCodeEswatini                         ISORegionCode = "SZ" // Eswatini 斯威士兰
	RegionCodeTurksCaicosIslands               ISORegionCode = "TC" // Turks and Caicos Islands 特克斯和凯科斯群岛
	RegionCodeChad                             ISORegionCode = "TD" // Chad 乍得
	RegionCodeFrenchSouthernTerritories        ISORegionCode = "TF" // French Southern Territories 法属南部领地
	RegionCodeTogo                             ISORegionCode = "TG" // Togo 多哥
	RegionCodeThailand                         ISORegionCode = "TH" // Thailand 泰国
	RegionCodeTajikistan                       ISORegionCode = "TJ" // Tajikistan 塔吉克斯坦
	RegionCodeTokelau                          ISORegionCode = "TK" // Tokelau 托克劳
	RegionCodeTimorLeste                       ISORegionCode = "TL" // Timor-Leste 东帝汶
	RegionCodeTurkmenistan                     ISORegionCode = "TM" // Turkmenistan 土库曼斯坦
	RegionCodeTunisia                          ISORegionCode = "TN" // Tunisia 突尼斯
	RegionCodeTonga                            ISORegionCode = "TO" // Tonga 汤加
	RegionCodeTurkey                           ISORegionCode = "TR" // Turkey 土耳其
	RegionCodeTrinidadTobago                   ISORegionCode = "TT" // Trinidad and Tobago 特立尼达和多巴哥
	RegionCodeTuvalu                           ISORegionCode = "TV" // Tuvalu 图瓦卢
	RegionCodeTaiwan                           ISORegionCode = "TW" // Taiwan 中国台湾
	RegionCodeTanzania                         ISORegionCode = "TZ" // Tanzania 坦桑尼亚
	RegionCodeUkraine                          ISORegionCode = "UA" // Ukraine 乌克兰
	RegionCodeUganda                           ISORegionCode = "UG" // Uganda 乌干达
	RegionCodeUnitedStatesMinorOutlyingIslands ISORegionCode = "UM" // United States Minor Outlying Islands 美国本土外小岛屿
	RegionCodeUnitedStates                     ISORegionCode = "US" // United States 美国
	RegionCodeUruguay                          ISORegionCode = "UY" // Uruguay 乌拉圭
	RegionCodeUzbekistan                       ISORegionCode = "UZ" // Uzbekistan 乌兹别克斯坦
	RegionCodeVaticanCity                      ISORegionCode = "VA" // Vatican City 梵蒂冈
	RegionCodeSaintVincentGrenadines           ISORegionCode = "VC" // Saint Vincent and the Grenadines 圣文森特和格林纳丁斯
	RegionCodeVenezuela                        ISORegionCode = "VE" // Venezuela 委内瑞拉
	RegionCodeBritishVirginIslands             ISORegionCode = "VG" // British Virgin Islands 英属维尔京群岛
	RegionCodeUSVirginIslands                  ISORegionCode = "VI" // U.S. Virgin Islands 美属维尔京群岛
	RegionCodeVietnam                          ISORegionCode = "VN" // Vietnam 越南
	RegionCodeVanuatu                          ISORegionCode = "VU" // Vanuatu 瓦努阿图
	RegionCodeWallisFutuna                     ISORegionCode = "WF" // Wallis and Futuna 瓦利斯和富图纳
	RegionCodeSamoa                            ISORegionCode = "WS" // Samoa 萨摩亚
	RegionCodeKosovo                           ISORegionCode = "XK" // Kosovo 科索沃
	RegionCodeYemen                            ISORegionCode = "YE" // Yemen 也门
	RegionCodeMayotte                          ISORegionCode = "YT" // Mayotte 马约特
	RegionCodeSouthAfrica                      ISORegionCode = "ZA" // South Africa 南非
	RegionCodeZambia                           ISORegionCode = "ZM" // Zambia 赞比亚
	RegionCodeZimbabwe                         ISORegionCode = "ZW" // Zimbabwe 津巴布韦
)
